원문: Moler, Cleve B. Numerical computing with MATLAB. Society for Industrial and Applied Mathematics, 2008.

# 1.4 마방진

마방진은 흥미로운 예제 행렬이다.

In [14]:
# scipython.com/book/chapter-6-numpy/examples/creating-a-magic-square/
import numpy as np


def magic(N):
    magic_square = np.matrix(np.zeros((N, N), dtype=int))
    
    n = 1
    i, j = 0, N//2
    
    while n <= N ** 2:
        magic_square[i, j] = n
        n += 1
        newi, newj = (i - 1) % N, (j + 1) % N
        if magic_square[newi, newj]:
            i += 1
        else:
            i, j = newi, newj
    
    return magic_square

A = magic(3)
A

matrix([[8, 1, 6],
        [3, 5, 7],
        [4, 9, 2]])

아래 명령은 모든 요소의 합을 계산한다.

In [3]:
np.sum(A)

45

아래 명령은 각 

In [5]:
np.sum(A, 0)

matrix([[15, 15, 15]])

각 행의 합은 다음과 같이 구한다.

In [7]:
np.sum(A, 1)

matrix([[15],
        [15],
        [15]])

In [9]:
np.sum(np.diag(A))

15

In [10]:
np.sum(np.diag(np.flipud (A)))

15

따라서 모든 합이 같다는 것을 확인할 수 있다.

왜 합은 15인가? 아래 명령

In [11]:
sum(np.arange(1, 9+1))

45

은 1 부터 9 까지의 정수의 합이 45임을 말한다. 이 정수들이 3 열에 나누어지고 합계가 같다면 그 합은

In [12]:
sum(np.arange(1, 9+1)) / 3

15.0

15가 될 것이다.

OHP 에 투명지를 올려놓는 방법은 모두 8가지가 있다. 비슷하게, 3렬의 마방진을 배열하는 8가지 방법이 있다.

In [16]:
for k in range(0, 4):
    print(np.rot90(A, k))
    print(np.rot90(A.T, k))

[[8 1 6]
 [3 5 7]
 [4 9 2]]
[[8 3 4]
 [1 5 9]
 [6 7 2]]
[[6 7 2]
 [1 5 9]
 [8 3 4]]
[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[2 9 4]
 [7 5 3]
 [6 1 8]]
[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[4 3 8]
 [9 5 1]
 [2 7 6]]
[[6 1 8]
 [7 5 3]
 [2 9 4]]


이제 선형 대수를 좀 살펴보자. 행렬식은 다음과 같다.

In [19]:
import numpy.linalg as na
na.det(A)

-359.99999999999972

역행렬은

In [20]:
X = A.I
X

matrix([[ 0.14722222, -0.14444444,  0.06388889],
        [-0.06111111,  0.02222222,  0.10555556],
        [-0.01944444,  0.18888889, -0.10277778]])

이다. 분수 형태로 표시하는 것이 더 낫다.

In [23]:
import fractions
print_option_backup_dict = np.get_printoptions()
np.set_printoptions(formatter={'all': lambda x: str(fractions.Fraction(x).limit_denominator())})
print(X)
np.set_printoptions(print_option_backup_dict)

[[53/360 -13/90 23/360]
 [-11/180 1/45 19/180]
 [-7/360 17/90 -37/360]]
