원문: Moler, Cleve B. Numerical computing with MATLAB. Society for Industrial and Applied Mathematics, 2008.

# 1.4 마방진

마방진은 흥미로운 예제 행렬이다.

In [1]:
import numpy as np


def magic(N):
    if (N % 2):
        result = magic_odd(N)
    else:
        result = magic_even(N)
    return result


def magic_odd(N):
    # scipython.com/book/chapter-6-numpy/examples/creating-a-magic-square/
    magic_square = np.matrix(np.zeros((N, N), dtype=int))
    
    n = 1
    i, j = 0, N//2
    
    while n <= N ** 2:
        magic_square[i, j] = n
        n += 1
        newi, newj = (i - 1) % N, (j + 1) % N
        if magic_square[newi, newj]:
            i += 1
        else:
            i, j = newi, newj
    
    return magic_square


def magic_even(N):
    # https://m.blog.naver.com/askmrkwon/220768685076 (in Korean)
    magic_ascending = np.array(range(1, N**2 + 1)).reshape((N, N))
    magic_descending = np.array(range(N**2, 0, -1)).reshape((N, N))
    
    print(magic_ascending)
    print(magic_descending)

A = magic(3)
A

matrix([[8, 1, 6],
        [3, 5, 7],
        [4, 9, 2]])

아래 명령은 모든 요소의 합을 계산한다.

In [2]:
np.sum(A)

45

각 열의 합은 아래 명령으로 계산한다.

In [3]:
np.sum(A, 0)

matrix([[15, 15, 15]])

각 행의 합은 다음과 같이 구한다.

In [4]:
np.sum(A, 1)

matrix([[15],
        [15],
        [15]])

다음은 주대각선의 합을 계산한다.

In [5]:
np.sum(np.diag(A))

15

반 대각선은 오른쪽 위에서 왼쪽 아래를 잇는 대각선으로, 선형 대수에서는 중요성이 덜하기 때문에, 합을 구하는 절차가 다소 복잡히다. 한가지 방법은 행렬을 위아래로 뒤집는 함수를 사용하는 것이다.

In [6]:
np.sum(np.diag(np.flipud (A)))

15

따라서 모든 합이 같다는 것을 확인할 수 있다.

왜 합은 15인가? 아래 명령

In [7]:
sum(np.arange(1, 9+1))

45

은 1 부터 9 까지의 정수의 합이 45임을 말한다. 이 정수들이 3 열에 나누어지고 합계가 같다면 그 합은

In [8]:
sum(np.arange(1, 9+1)) / 3

15.0

15가 될 것이다.

OHP 에 투명지를 올려놓는 방법은 모두 8가지가 있다. 비슷하게, 3렬의 마방진을 배열하는 8가지 방법이 있다.  아래 명령은 각각의 방법을 모두 표시한다.

In [9]:
for k in range(0, 4):
    print(np.rot90(A, k))
    print(np.rot90(A.T, k))

[[8 1 6]
 [3 5 7]
 [4 9 2]]
[[8 3 4]
 [1 5 9]
 [6 7 2]]
[[6 7 2]
 [1 5 9]
 [8 3 4]]
[[4 9 2]
 [3 5 7]
 [8 1 6]]
[[2 9 4]
 [7 5 3]
 [6 1 8]]
[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[4 3 8]
 [9 5 1]
 [2 7 6]]
[[6 1 8]
 [7 5 3]
 [2 9 4]]


이제 선형 대수를 좀 살펴보자. 행렬식은 다음과 같다.

In [10]:
import numpy.linalg as na
na.det(A)

-359.99999999999972

역행렬은

In [11]:
X = A.I
X

matrix([[ 0.14722222, -0.14444444,  0.06388889],
        [-0.06111111,  0.02222222,  0.10555556],
        [-0.01944444,  0.18888889, -0.10277778]])

이다. 분수 형태로 표시할 수 있다면 더 좋다.

In [12]:
import fractions
np.set_printoptions(formatter={'all': lambda x: str(fractions.Fraction(x).limit_denominator())})
print(X)

[[53/360 -13/90 23/360]
 [-11/180 1/45 19/180]
 [-7/360 17/90 -37/360]]


아래와 같이 하면 원상 복귀 될 것이다.

In [13]:
np.set_printoptions(formatter=None)

전산 선형 대수에서 중요한 3가지 값으로 행렬의 놂, 고유치, 특이값 등이 있다.

In [23]:
r = na.norm(A, np.inf)
e, w = na.eig(A)
u, s, v_h = na.svd(A)
print('r =')
print(r)
print('e =')
print(e)
print('s =')
print(s)

r =
15.0
e =
[ 15.           4.89897949  -4.89897949]
s =
[ 15.           6.92820323   3.46410162]


마방진의 한 열의 합은 위 3 값에서 모두 나타난다. 고유 벡터 (아래의 w), 좌 우 특이 벡터 (각각 아래의 u, v) 가운데 하나는 모두 1인 것이 있기 때문이다. (w, u, v 의 각 열 가운데 하나씩은 모든 항의 값이 같음)

In [24]:
print('w =')
print(w)
print('u =')
print(u)
print('v =')
print(v_h.H)

w =
[[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]
u =
[[ -5.77350269e-01   7.07106781e-01   4.08248290e-01]
 [ -5.77350269e-01   5.96744876e-15  -8.16496581e-01]
 [ -5.77350269e-01  -7.07106781e-01   4.08248290e-01]]
v =
[[ -5.77350269e-01   4.08248290e-01   7.07106781e-01]
 [ -5.77350269e-01  -8.16496581e-01  -1.16573418e-14]
 [ -5.77350269e-01   4.08248290e-01  -7.07106781e-01]]


지금까지 이 절의 모든 연산은 부동소숫점이었다. 대부분의 과학 기술 계산, 특히 큰 행렬의 연산은 이렇게 한다. 하지만 $3\times3$

In [22]:
import sympy as sy

A = sy.Matrix(A)
A

Matrix([
[8.0, 1.0, 6.0],
[3.0, 5.0, 7.0],
[4.0, 9.0, 2.0]])

In [28]:
print('np.sum(A) = %r' % np.sum(A))
print('np.sum(A, 0) = %r' % np.sum(A, 0))
print('np.sum(A, 1) = %r' % np.sum(A, 1))
print('sy.det(A) = %r' % sy.det(A))
print('A.eigenvals() = %r' % A.eigenvals())
print('A.singular_values() = %r' % A.singular_values())

np.sum(A) = 45.0000000000000
np.sum(A, 0) = array([15.0000000000000, 15.0000000000000, 15.0000000000000], dtype=object)
np.sum(A, 1) = array([15.0000000000000, 15.0000000000000, 15.0000000000000], dtype=object)
sy.det(A) = -360.000000000000
A.eigenvals() = {2*sqrt(6): 1, -2*sqrt(6): 1, 15: 1}
A.singular_values() = [4*sqrt(3), 2*sqrt(3), 15]
